// This file was generated by Cobalt's Config parser based on the configuration
// YAML in the cobalt_config repository. Edit the YAML there to make changes.
// Metric ID Constants
// the_metric_name
// ignore: constant_identifier_names
const int kTheMetricNameMetricId = 238615413;
// the_other_metric_name
// ignore: constant_identifier_names
const int kTheOtherMetricNameMetricId = 2739731282;

// Enum for the_other_metric_name (EventCode)
class TheOtherMetricNameEventCode {
  static const int AnEvent = 0;
  static const int AnotherEvent = 1;
  static const int AThirdEvent = 2;
}
const int TheOtherMetricNameEventCode_AnEvent = TheOtherMetricNameEventCode::AnEvent;
const int TheOtherMetricNameEventCode_AnotherEvent = TheOtherMetricNameEventCode::AnotherEvent;
const int TheOtherMetricNameEventCode_AThirdEvent = TheOtherMetricNameEventCode::AThirdEvent;

// The base64 encoding of the bytes of a serialized CobaltConfig proto message.
const String config = 'KtsBCghjdXN0b21lchAKGswBCgdwcm9qZWN0EAUaTQoPdGhlX21ldHJpY19uYW1lEAoYBSD19uNxYhUKCnRoZV9yZXBvcnQQu6WL8QgYj05iGgoQdGhlX290aGVyX3JlcG9ydBDK3M3qARgGGnAKFXRoZV9vdGhlcl9tZXRyaWNfbmFtZRAKGAUg0vazmgooATILCAASB0FuRXZlbnQyEAgBEgxBbm90aGVyRXZlbnQyEQgCEg1BIHRoaXJkIGV2ZW50OMgBUAFiFAoKdGhlX3JlcG9ydBC7pYvxCBgH';
